//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoliosis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScoliosisStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScoliosisStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scoliosis.ScoliosisStrings", typeof(ScoliosisStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente sair do sistema ?.
        /// </summary>
        internal static string MSG0001 {
            get {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválida..
        /// </summary>
        internal static string MSG0002 {
            get {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        internal static string MSG0003 {
            get {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [Nova Senha] não pode ficar em branco..
        /// </summary>
        internal static string MSG0004 {
            get {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [Confirmar Senha] deve ser igual ao campo [Nova Senha]..
        /// </summary>
        internal static string MSG0005 {
            get {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual inválida..
        /// </summary>
        internal static string MSG0006 {
            get {
                return ResourceManager.GetString("MSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atualizada com sucesso..
        /// </summary>
        internal static string MSG0007 {
            get {
                return ResourceManager.GetString("MSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar conexão com o dispositivo selecionado..
        /// </summary>
        internal static string MSG0008 {
            get {
                return ResourceManager.GetString("MSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na aquisição da imagem..
        /// </summary>
        internal static string MSG0009 {
            get {
                return ResourceManager.GetString("MSG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente não encontrado..
        /// </summary>
        internal static string MSG0010 {
            get {
                return ResourceManager.GetString("MSG0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na leitura da imagem..
        /// </summary>
        internal static string MSG0011 {
            get {
                return ResourceManager.GetString("MSG0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível identificar todos os pontos de referência..
        /// </summary>
        internal static string MSG0012 {
            get {
                return ResourceManager.GetString("MSG0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato inválido ou número de pontos insuficientes..
        /// </summary>
        internal static string MSG0013 {
            get {
                return ResourceManager.GetString("MSG0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos de referência inválidos..
        /// </summary>
        internal static string MSG0014 {
            get {
                return ResourceManager.GetString("MSG0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível calcular os parâmetros da transformação. A ordem dos pontos pode estar incorreta..
        /// </summary>
        internal static string MSG0015 {
            get {
                return ResourceManager.GetString("MSG0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ponto {0} não foi selecionado..
        /// </summary>
        internal static string MSG0016 {
            get {
                return ResourceManager.GetString("MSG0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a transformação dos pontos..
        /// </summary>
        internal static string MSG0017 {
            get {
                return ResourceManager.GetString("MSG0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem não encontrada..
        /// </summary>
        internal static string MSG0018 {
            get {
                return ResourceManager.GetString("MSG0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação armazenada com sucesso..
        /// </summary>
        internal static string MSG0019 {
            get {
                return ResourceManager.GetString("MSG0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente cancelar a avaliação ?.
        /// </summary>
        internal static string MSG0020 {
            get {
                return ResourceManager.GetString("MSG0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a comunicação com a porta serial. Verifique as configurações no menu Ferramentas &gt; Opções..
        /// </summary>
        internal static string MSG0021 {
            get {
                return ResourceManager.GetString("MSG0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre com um peso válido (maior que 5kg e menor do que 200kg)..
        /// </summary>
        internal static string MSG0022 {
            get {
                return ResourceManager.GetString("MSG0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [Nome] não pode ficar em branco..
        /// </summary>
        internal static string MSG0023 {
            get {
                return ResourceManager.GetString("MSG0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [CPF] não pode ficar em branco..
        /// </summary>
        internal static string MSG0024 {
            get {
                return ResourceManager.GetString("MSG0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [E-mail] é inválido..
        /// </summary>
        internal static string MSG0025 {
            get {
                return ResourceManager.GetString("MSG0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o paciente ?.
        /// </summary>
        internal static string MSG0026 {
            get {
                return ResourceManager.GetString("MSG0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cálculo armazenado com sucesso..
        /// </summary>
        internal static string MSG0027 {
            get {
                return ResourceManager.GetString("MSG0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [Login] não pode ficar em branco..
        /// </summary>
        internal static string MSG0028 {
            get {
                return ResourceManager.GetString("MSG0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo [Senha] não pode ficar em branco..
        /// </summary>
        internal static string MSG0029 {
            get {
                return ResourceManager.GetString("MSG0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente alterar a senha do usuário ?.
        /// </summary>
        internal static string MSG0030 {
            get {
                return ResourceManager.GetString("MSG0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o usuário ?.
        /// </summary>
        internal static string MSG0031 {
            get {
                return ResourceManager.GetString("MSG0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cálculo do IMC não encontrado..
        /// </summary>
        internal static string MSG0032 {
            get {
                return ResourceManager.GetString("MSG0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação não encontrada..
        /// </summary>
        internal static string MSG0033 {
            get {
                return ResourceManager.GetString("MSG0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro angular inválido..
        /// </summary>
        internal static string MSG0034 {
            get {
                return ResourceManager.GetString("MSG0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir a avaliação ?.
        /// </summary>
        internal static string MSG0035 {
            get {
                return ResourceManager.GetString("MSG0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o cálculo do IMC ?.
        /// </summary>
        internal static string MSG0036 {
            get {
                return ResourceManager.GetString("MSG0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Escoliose não detectado.
        /// </summary>
        internal static string MSGTIPOESC00 {
            get {
                return ResourceManager.GetString("MSGTIPOESC00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string MSGTIPOESC01 {
            get {
                return ResourceManager.GetString("MSGTIPOESC01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Simples Dorsal/Torácica Direita.
        /// </summary>
        internal static string MSGTIPOESC02 {
            get {
                return ResourceManager.GetString("MSGTIPOESC02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Simples Dorsal/Torácica Esquerda.
        /// </summary>
        internal static string MSGTIPOESC03 {
            get {
                return ResourceManager.GetString("MSGTIPOESC03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Simples Lombar Direita.
        /// </summary>
        internal static string MSGTIPOESC04 {
            get {
                return ResourceManager.GetString("MSGTIPOESC04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose  Simples Lombar Esquerda.
        /// </summary>
        internal static string MSGTIPOESC05 {
            get {
                return ResourceManager.GetString("MSGTIPOESC05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Total Direita.
        /// </summary>
        internal static string MSGTIPOESC06 {
            get {
                return ResourceManager.GetString("MSGTIPOESC06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Total Esquerda.
        /// </summary>
        internal static string MSGTIPOESC07 {
            get {
                return ResourceManager.GetString("MSGTIPOESC07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Tripla Lombar Direita Cervical Direita Dorsal Esquerda.
        /// </summary>
        internal static string MSGTIPOESC08 {
            get {
                return ResourceManager.GetString("MSGTIPOESC08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Tripla Lombar Esquerda Cervical Esquerda Dorsal Direita.
        /// </summary>
        internal static string MSGTIPOESC09 {
            get {
                return ResourceManager.GetString("MSGTIPOESC09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Dupla Dorsal Esquerda Lombar Direita.
        /// </summary>
        internal static string MSGTIPOESC10 {
            get {
                return ResourceManager.GetString("MSGTIPOESC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoliose Dupla Dorsal Direita Lombar Esquerda.
        /// </summary>
        internal static string MSGTIPOESC11 {
            get {
                return ResourceManager.GetString("MSGTIPOESC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desnutrição crônica.
        /// </summary>
        internal static string MSGTIPOIMC01 {
            get {
                return ResourceManager.GetString("MSGTIPOIMC01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desnutrição.
        /// </summary>
        internal static string MSGTIPOIMC02 {
            get {
                return ResourceManager.GetString("MSGTIPOIMC02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixo peso.
        /// </summary>
        internal static string MSGTIPOIMC03 {
            get {
                return ResourceManager.GetString("MSGTIPOIMC03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string MSGTIPOIMC04 {
            get {
                return ResourceManager.GetString("MSGTIPOIMC04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obeso Grau 1.
        /// </summary>
        internal static string MSGTIPOIMC05 {
            get {
                return ResourceManager.GetString("MSGTIPOIMC05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obeso Grau 2.
        /// </summary>
        internal static string MSGTIPOIMC06 {
            get {
                return ResourceManager.GetString("MSGTIPOIMC06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obeso Grau 3.
        /// </summary>
        internal static string MSGTIPOIMC07 {
            get {
                return ResourceManager.GetString("MSGTIPOIMC07", resourceCulture);
            }
        }
    }
}
